name: cyber_os
description: Advanced Cyber Security Intelligence & Toolkit Application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Çekirdek Paketler ---
  flutter_riverpod: ^2.4.9  # State Management
  dio: ^5.4.0               # HTTP İstekleri
  hive: ^2.2.3              # Veritabanı
  hive_flutter: ^1.1.0      # Flutter için Hive
  
  # --- Araçlar & Yardımcılar ---
  crypto: ^3.0.3            # MD5, SHA256, HMAC vb.
  intl: ^0.19.0             # Tarih Formatlama
  
  # --- Görsel & UI ---
  google_fonts: ^6.1.0      # Orbitron, RobotoMono vb.
  percent_indicator: ^4.2.3 # Risk Yuvarlağı
  cupertino_icons: ^1.0.6   # Standart İkonlar
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

  # --- Kod Üreticileri ---
  build_runner: ^2.4.8      # Hive için gerekli
  hive_generator: ^2.0.1    # Hive kod üreticisi

  # --- Market Hazırlığı (Launch Tools) ---
  flutter_launcher_icons: ^0.13.1      # Uygulama İkonunu Değiştirir
  flutter_native_splash: ^2.3.1        # Açılış Ekranını Değiştirir

# --- İKON AYARLARI ---
# Proje klasöründe 'assets' diye klasör açıp içine 'icon.png' atarsan çalışır.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# --- AÇILIŞ EKRANI AYARLARI ---
flutter_native_splash:
  color: "#000000"           # Simsiyah arka plan
  image: "assets/icon.png"   # Ortada logon duracak
  android_12:
    color: "#000000"
    image: "assets/icon.png"

flutter:
  uses-material-design: true

assets:
    - assets/